chat/urls.py
from django.urls import path
from chat.views.views import *

app_name = 'chats'

urlpatterns = [
    path('chat/<int:pk>/', chatroom, name='chatroom'),
    path('chat/ajax/<int:pk>/', ajax_load_messages, name='chatroom-ajax'),
    path('chatpage', chatpage, name='chatpage'),
]

myhome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static
from predict import urls as predict_urls
from posts import urls as posts_url
from homeauth import urls as homeauth_urls
from chat import urls as chat_urls

app_name = 'myhome'
urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', views.start, name='start'),
                  # path('home', views.home, name='home'),
                  # path('login', views.login, name='login'),
                  path('', include(predict_urls, namespace='predict')),
                  path('', include(posts_url, namespace='posts')),
                  path('', include(homeauth_urls, namespace='homeauth')),
                  path('', include(chat_urls, namespace='chats')),
              ] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    message = models.TextField()
    seen = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_created',)

chat/views/views.py
from django.shortcuts import render, get_object_or_404
from django.http.response import JsonResponse
from chat.models.models import Message, User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
import json


@login_required
def chatroom(request, pk: int):
    other_user = get_object_or_404(User, pk=pk)
    messages = Message.objects.filter(
        Q(sender=request.user, receiver=other_user) | Q(sender=other_user, receiver=request.user)
    )
    messages.update(seen=True)

    # For chatpage
    current_user = request.user
    receiver_ids_sent = Message.objects.filter(sender=current_user).values_list('receiver', flat=True).distinct()
    sender_ids_received = Message.objects.filter(receiver=current_user).values_list('sender', flat=True).distinct()
    combined_user_ids = set(receiver_ids_sent) | set(sender_ids_received)
    users_info = User.objects.filter(id__in=combined_user_ids).values('id', 'username', 'first_name', 'last_name')

    return render(request, 'chat/chatroom.html',
                  {'other_user': other_user, 'messages': messages, 'users_info': users_info, 'user': current_user})


@login_required
def ajax_load_messages(request, pk):
    other_user = get_object_or_404(User, pk=pk)
    messages = Message.objects.filter(seen=False).filter(Q(sender=other_user, receiver=request.user))

    message_list = [{
        "sender": message.sender.username,
        "receiver": message.receiver.username,
        "sent": message.sender == request.user,
    } for message in messages]
    messages.update(seen=True)
    if request.method == 'POST':
        message = json.loads(request.body.decode('utf-8'))
        m = Message.objects.create(sender=request.user, receiver=other_user, message=message)
        message_list.append({
            "sender": request.user.username,
            "message": m.message,
            "sent": True,
        })
    return JsonResponse(message_list, safe=False)


def chatpage(request):
    current_user = request.user

    # Retrieve distinct receiver IDs where the current user is the sender
    receiver_ids_sent = Message.objects.filter(sender=current_user).values_list('receiver', flat=True).distinct()

    # Retrieve distinct sender IDs where the current user is the receiver
    sender_ids_received = Message.objects.filter(receiver=current_user).values_list('sender', flat=True).distinct()

    # Combine the sender and receiver IDs
    combined_user_ids = set(receiver_ids_sent) | set(sender_ids_received)

    # Retrieve user IDs and usernames associated with combined IDs
    users_info = User.objects.filter(id__in=combined_user_ids).values('id', 'username', 'first_name', 'last_name')

    return render(request, 'chat/chatpage.html', {'users_info': users_info, 'user': current_user})

chat/templates/chat/chatpage.html
{% extends 'base.html' %}
{% block title %} Chats {% endblock %}
{% block content %}
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
          font-family: "Raleway", sans-serif;
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          text-decoration: none;
          outline: none;
          border: none;
        }
        
        body {
          max-height: fit-content;
          background-color: #12141D;
          background-attachment: fixed;
          background-position: center;
          overflow-x: hidden;
        }

        {% comment %} .header {
            padding: 10px 5%;
            background: #e5c82c;
            color: #000000;
            width: 127%;
        }

        .header-left {
            padding: 10px 5%;
            background: #e5c82c;
            color: #020202;
            width: 60%;
        } {% endcomment %}

        .messages-area {
            height: 70vh; /* Fixed height for the messages area */
            overflow-y: auto;
            background: #d9dadb;
            color: #999;
            padding: 4% 4% 10px;
            width: 127%;
        }

        .messages-area-left {
            height: 81.1vh; /* Fixed height for the messages area */
            overflow-y: auto;
            background: #282525;
            color: #999;
            padding: 4% 4% 10px;
            width: 60%;
        }

        .input-area {
            display: flex;
            flex-direction: row;
            justify-content: center;
            width: 127%;
        }

        #message-input {
            padding: 10px;
            width: 100%;
            height: 50%;
        }

        .message.left {
            text-align: left;
            color: #aaa;
        }

        .message.right {
            text-align: right;
            color: #ccc;
        }

        .message .content {
            background: #444;
            padding: 5px 10px;
            border-radius: 10px;
            max-width: 80%;
            display: inline-block;
        }
    </style>
    <div class="mx-auto max-w-7xl grid 2xl:grid-cols-2 xl:grid-cols-2 lg:grid-cols-2 md:grid-cols-2 sm:grid-cols-1 gap-4 rounded-xl my-20 border border-amber-200">
        <!-- Contacts Section -->
        <div class="bg-[#1E2029] p-6 lg:h-[400px] sm:h-[200px] rounded-md">
            <div class="text-white text-2xl mb-4">All Contacts</div>
            <div class="py-2 px-6 overflow-y-auto h-[300px]">
                {% for user in users_info %}
                <h6 class="mt-4">
                    <a href="{% url 'chats:chatroom' user.id %}" class="text-white hover:text-amber-500">
                        {{ user.first_name }} {{ user.last_name }}
                    </a>
                </h6>
                {% endfor %}
            </div>
        </div>
    
        <!-- Chat Section -->
        <div class="bg-[#f3f3f3] rounded-md h-[400px] ">
            <!-- Placeholder when no chat is selected -->
            <div class="pt-4 text-center text-gray-700 text-xl  h-[345px] flex flex-col justify-center">
                Select a profile from contacts to chat!
            </div>
    
            <!-- Chat Area -->
            <div class="py-2 px-6 h-[200px] overflow-y-auto hidden" id="messages-area">
                {% for message in messages %}
                <div class="message {% if message.sender == request.user %}text-right{% else %}text-left{% endif %}">
                    <div class="sent-by text-gray-600">
                        {% if message.sender == request.user %}Me{% else %}
                        {{ message.sender.first_name }}{% endif %}
                    </div>
                    <div class="content bg-white p-2 rounded-lg shadow-md">
                        {{ message.message }}
                    </div>
                </div>
                {% endfor %}
            </div>
    
            <!-- Input Area (fixed at bottom) -->
            <div class=" bottom-0 left-0 w-full flex items-center bg-white border-t border-gray-300">
                <input type="text" id="message-input" class="flex-grow p-2 border border-gray-300 rounded" placeholder="Type a message">
                <button id="send-btn" class="ml-2 bg-amber-500 text-white px-2 py-4 rounded hover:bg-amber-600">Send</button>
            </div>
        </div>
    </div>
    
{% endblock %}

chat/templates/chat/chatroom.html
{% extends 'base.html' %}
{% block title %} Chats {% endblock %}
{% block content %}
    <style>
 

        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
          font-family: "Raleway", sans-serif;
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          text-decoration: none;
          outline: none;
          border: none;
        }
        
        body {
          max-height: fit-content;
          background-color: #12141D;
          background-attachment: fixed;
          background-position: center;
          overflow-x: hidden;
        }

        .messages-area {
            height: 75vh; /* Fixed height for the messages area */
            overflow-y: auto;
            background: #d9dadb;
            color: #999;
            padding: 4% 4% 10px;
            width: 127%;
        }

        .messages-area-left {
            height: 81.1vh; /* Fixed height for the messages area */
            overflow-y: auto;
            background: #282525;
            color: #999;
            padding: 4% 4% 10px;
            width: 60%;
        }

        .input-area {
            display: flex;
            flex-direction: row;
            justify-content: center;
            width: 127%;
        }

        #message-input {
            padding: 10px;
            width: 100%;
            height: 50%;
        }
        .message.left {
            text-align: left;
            color: #aaa;
        }

        .message.right {
            text-align: right;
            color: #ccc;
        }

        .message .content {
            background: #444;
            padding: 5px 10px;
            border-radius: 10px;
            max-width: 80%;
            display: inline-block;
        }
    </style>
    <div class="mx-auto max-w-7xl grid 2xl:grid-cols-2 xl:grid-cols-2 lg:grid-cols-2 md:grid-cols-1 sm:grid-cols-1 gap-4 rounded-xl my-20 border border-amber-200 ">
        <!-- Contacts Section -->
        <div class="bg-[#1E2029] p-6 lg:h-[400px] sm:h-[250px] rounded-md">
            <div class="text-white text-2xl mb-4">All Contacts</div>
            <div>
                {% for user in users_info %}
                <h6>
                    <a href="{% url 'chats:chatroom' user.id %}" class="text-white hover:text-amber-500">
                        {{ user.first_name }} {{ user.last_name }}
                    </a>
                </h6>
                {% endfor %}
            </div>
        </div>
    
        <!-- Chat Section -->
        <div class="bg-[#f3f3f3] h-[400px] rounded-md">
            <!-- Chat Header -->
            <div class="bg-gray-500 p-4 font-bold text-white border-b-2 border-gray-700">
                {{ other_user.first_name }} {{ other_user.last_name }}
            </div>
            <!-- Messages Area -->
            <div class="p-4 h-[304px] overflow-y-auto " id="messages-area">
                {% for message in messages %}
                <div class="message {% if message.sender == request.user %}text-right{% else %}text-left{% endif %}">
                    <div class="sent-by text-gray-600">
                        {% if message.sender == request.user %}Me{% else %}
                        {{ message.sender.first_name }}{% endif %}
                    </div>
                    <div class="content text-white bg-white p-2 rounded-lg shadow-md">{{ message.message }}</div>
                </div>
                {% endfor %}
            </div>
            <!-- Input Area -->
            <div class="flex items-center border-t border-gray-300">
                <input type="text" id="message-input" class="p-4 border rounded border-gray-300" placeholder="Type a message">
                <button id="send-btn" class="  bg-amber-500 rounded text-white px-4 py-2">Send</button>
            </div>
        </div>
    </div>
    
    <script>

        let message_send_btn = document.getElementById("send-btn");
        let message_input = document.getElementById("message-input");
        let messagesContainer = document.getElementById("messages-area");

        function send_message() {
            let message = message_input.value;
            if (message === "") {
                return;
            }
            message_input.value = "";
            // Send the message and update the chat
            fetch("{% url 'chats:chatroom-ajax' other_user.id %}", {
                method: "POST",
                credentials: 'same-origin',
                headers: {
                    "Content-Type": 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify(message)
            }).then(e => e.json()).then(messages => {
                for (message of messages) {
                    construct_message(message);
                }
            });
        }

        function load_messages() {
            // Load initial messages and update the chat
            fetch("{% url 'chats:chatroom-ajax' other_user.id %}")
                .then(e => e.json())
                .then(messages => {
                    for (message of messages) {
                        construct_message(message);
                    }
                });
        }

        function construct_message(message) {
            let class_name = "left";
            if (message.sent) {
                class_name = "right";
            }
            let div = document.createElement("div");
            div.classList.add("message", class_name);
            div.innerHTML = `
        <div class="sent-by">Me</div>
        <div class="content">${message.message}</div>
        `;
            messagesContainer.appendChild(div);

            // Scroll to the latest message
            messagesContainer.scrollTop = messagesContainer.scrollHeight;
        }

        message_send_btn.addEventListener('click', send_message);
        setInterval(load_messages, 2000);

    </script>
{% endblock %}