chat/urls.py
from django.urls import path
from chat.views.views import *

app_name = 'chats'

urlpatterns = [
    path('chat/<int:pk>/', chatroom, name='chatroom'),
    path('chat/ajax/<int:pk>/', ajax_load_messages, name='chatroom-ajax'),
    path('chatpage', chatpage, name='chatpage'),
]

homeauth/urls.py
from django.urls import path
from homeauth.views import views
from homeauth.views.views import PasswordsChangeView

app_name = 'homeauth'
urlpatterns = [
    path('signup', views.signUp, name='signup'),
    path('login', views.logIn, name='login'),
    path('logout', views.logOut, name='logout'),
    path('edit-profile', views.EditProfilePageView.as_view(), name='edit_profile'),
    path('<int:pk>/password/', PasswordsChangeView.as_view(), name='password'),
]

myhome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static
from predict import urls as predict_urls
from posts import urls as posts_url
from homeauth import urls as homeauth_urls
from chat import urls as chat_urls

app_name = 'myhome'
urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', views.start, name='start'),
                  # path('home', views.home, name='home'),
                  # path('login', views.login, name='login'),
                  path('', include(predict_urls, namespace='predict')),
                  path('', include(posts_url, namespace='posts')),
                  path('', include(homeauth_urls, namespace='homeauth')),
                  path('', include(chat_urls, namespace='chats')),
              ] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views.views import *

app_name = 'posts'

urlpatterns = [
    path('browse', BrowserView.as_view(), name='browse'),
    path('content/<int:pk>', PostDetailsView.as_view(), name='content'),
    path('new-post/', PostCreateView.as_view(), name='new_post'),
    path('content/update/<int:pk>', PostUpdateView.as_view(), name='update_post'),
    path('content/delete/<int:pk>', PostDeleteView.as_view(), name='delete_post'),
    path('filter', filter_posts, name='filter'),
    path('content/<int:pk>/comment/', CommentView.as_view(), name='comment'),
    path('content/<int:pk>/delete', CommentDeleteView.as_view(), name='deleteComment'),
    path('', home_auth, name='home'),
]

predict/urls.py
from django.urls import path
from predict.views import views

app_name = 'predict'
urlpatterns = [
    path('prediction', views.prediction, name='predict'),
    path('predict', views.prediction_result, name='prediction_result'),
    path('ehehbouy', views.location, name='ehehbouy'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> {% endcomment %}
    

      <!-- font awesome cdn link  -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">

  {% comment %} Tailwing css  {% endcomment %}
     <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" /> 
     <link href="https://cdn.jsdelivr.net/npm/tailwindcss@latest/dist/tailwind.min.css" rel="stylesheet">

    {% comment %} <link href="/dist/main.css" rel="stylesheet"> {% endcomment %}
    <style>
   @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

* {
  font-family: "Raleway", sans-serif;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  text-decoration: none;
  outline: none;
  border: none;
}

body {
  max-height: fit-content;
  background-color: #12141D;
  background-attachment: fixed;
  background-position: center;
  overflow-x: hidden;
}

.header {
   {% comment %} position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 1000;  {% endcomment %}
  background: #12141D;
  padding: 12px 6.5%;
}
    </style>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
        <!-- header section starts  -->
        <header class=" header  bg-[#12141D] border-b-2 border-white">
            <nav class="flex items-center justify-between px-12 h-16 lg:gap-8">

                {% if user.is_authenticated %}
                <div class="text-[#fff]">
                    <a href="{% url 'posts:home' %}" class="whitespace-nowrap">
                        House_Predic
                    </a>
                </div>
    
                <div
                    class="dropdown-menu absolute -top-full left-0 max-lg:bg-[#12141D] w-full flex flex-col gap-6 items-center py-3  lg:static lg:flex-row lg:justify-between">
                    <ul class="flex flex-col items-center gap-6 lg:flex-row lg:gap-8 text-[#fff]">
    
                        <li class=""><a href="{% url 'posts:home' %}"
                                class="text-[#FFFFFF] text-[13px] active:font-[600] font-[500]">Home</a></li>
                        <li class=""><a href="{% url 'posts:browse' %}" class="text-[#FFFFFF] text-[13px] font-[600]">Browse</a></li>
                        <li class=""><a href="{% url 'predict:predict' %}"
                            class="text-[#FFFFFF] text-[13px] font-[500]">Predict Price</a>
                        </li>
                        <li class=""><a href="" class="text-[#FFFFFF] text-[13px] font-[500]">About Us</a></li>
                        <li class=""><a href="{% url 'chats:chatpage' %}" class="text-[#FFFFFF] text-[13px] font-[500]">Chats</a></li>
    
                    </ul>
    
                    <div class=" items-center gap-6 lg:flex-row lg:gap-8">
                        <a href="{% url 'homeauth:edit_profile' %}" class="px-3 py-2 text-[13px] font-[600] text-gray-300 hover:bg-gray-700 hover:text-white mr-4 rounded font-bold">Profile</a>
                        <a href="{% url 'homeauth:logout' %}"
                            class="px-3 py-2 text-[13px] font-[600] text-black bg-white hover:bg-gray-700 hover:text-white rounded font-bold">Logout</a>
                    </div>
                </div>
    
                <div class="toggle-button text-[#fff] lg:hidden  cursor-pointer">
                    <i class="fa fa-bars fa-lg"></i>
                </div>

                {% else %}

                <div class="text-[#fff]">
                    <a href="#home" class="whitespace-nowrap">House_Predic</a>
                </div>
    
                <div
                    class="dropdown-menu absolute -top-full left-0 max-lg:bg-[#12141D] w-full flex flex-col gap-6 items-center py-3  lg:static lg:flex-row lg:justify-between">
                    <ul class="flex flex-col items-center gap-6 lg:flex-row lg:gap-8 text-[#fff]">
    
                        <li class=""><a href="{% url 'posts:home' %}"
                            class="text-[#FFFFFF] text-[13px] active:font-[600] font-[500]">Home</a></li>
                    <li class=""><a href="{% url 'posts:browse' %}" class="text-[#FFFFFF] text-[13px] font-[600]">Browse</a></li>
                    <li class=""><a href="prediction.html"
                        class="text-[#FFFFFF] text-[13px] font-[500]">Predict Price</a>
                    </li>
                    <li class=""><a href="" class="text-[#FFFFFF] text-[13px] font-[500]">About Us</a></li>
                    {% comment %} <li class=""><a href="{% url 'chats:chatpage' %}" class="text-[#FFFFFF] text-[13px] font-[500]">Chats</a></li> {% endcomment %}
    
                    </ul>
    
                    <div class=" items-center gap-6 lg:flex-row lg:gap-8">
                        <a href="{% url 'homeauth:login' %}"
                            class="px-3 py-2 text-[13px] font-[600] text-gray-300 hover:bg-gray-700 hover:text-white mr-4 rounded font-bold">Login</a>
                    </div>
                </div>
    
                <div class="toggle-button text-[#fff] lg:hidden cursor-pointer">
                    <i class="fa fa-bars fa-lg"></i>
                </div>

                {% endif %}
            </nav>
            <div>
                {% block content %}{% endblock %}
            </div>
        </header>
        <!-- header section ends  -->


<script>
    const toggleBtn = document.querySelector(".toggle-button");

    const dropdown = document.querySelector(".dropdown-menu");

    toggleBtn.addEventListener("click", () => {
        dropdown.classList.toggle('top-16');
    });

    var swiper = new Swiper(".testimonials-slider", {
        spaceBetween: 10,
        grabCursor: true,
        loop: true,
        centeredSlides: true,
        loop: true,
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        autoplay: {
            delay: 9500,
            disableOnInteraction: false,
        },
        breakpoints: {
            0: {
                slidesPerView: 1,
            },
            768: {
                slidesPerView: 2,
            },
            1024: {
                slidesPerView: 3,
            },
        },
    });
</script>

<script src="https://cdn.tailwindcss.com"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>

<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

</body>
</html>

templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get Started!</title>
    <style>
        body {
            background-color: #080710;
            filter: alpha(opacity=50);
        }
        .vl {
            border-left: 6px solid #ffffff;
            height: 200px;
            position: absolute;
            left: 50%;
            margin-left: -3px;
            top: 20%;
        }
        input[type=submit] {
            background-color: #238d0c;
            border: none;
            border-radius: 12px;
            color: white;
            padding: 16px 32px;
            text-decoration: none;
            {#margin-left: 45%;#}
            cursor: pointer;
            font-size: 20px;
            font-family: "Times New Roman", Times, serif;
        }


    </style>
</head>
<body>
    <h1 style = 'color: #ffffff; text-align: center'>You have to Log in First!</h1>
    <h2 style = 'color: #ffffff; position: absolute; left: 20%; top: 20%'>Already Have an Account?</h2>
    <form action="login">
        <input type="submit" value="Login" style="position: absolute; left: 25%; top: 30%">
    </form>


    <h2 style = 'color: #ffffff; position: absolute; left: 60%; top: 20%'>New User? You Have to Create an Account.</h2>
    <form action="signup">
        <input type="submit" value="SignUp" style="position: absolute; left: 73%; top: 30%">
    </form>
    <div class="vl"></div>
</body>
</html>

templates/prediction.html
{% extends 'base.html' %}
{% block title %} Prediction {% endblock %}
{% block content %}
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

* {
  font-family: "Raleway", sans-serif;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  text-decoration: none;
  outline: none;
  border: none;
}

body {
  max-height: fit-content;
  background-color: #12141D;
  background-attachment: fixed;
  background-position: center;
  overflow-x: hidden;
}
    </style>

    <div class="mx-auto  max-w-3xl my-16 py-14  px-2 sm:px-6 lg:px-8 my-20 p-6 bg-[#1E2029] rounded-lg shadow-lg">
        <h2 class="text-aqua text-2xl font-semibold mb-4 text-[#fff]">Calculate the price of a House according to requirements!</h2>
        <form action="predict" class="space-y-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="area" class="text-white text-lg">Area (Square Feet)</label>
                <input type="number" id="area" required name="area" class="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:border-blue-300">
            </div>
            <div class="form-group">
                <label for="bedroom" class="text-white text-lg">Bedroom</label>
                <input type="text" id="bedroom" required name="bedroom" class="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:border-blue-300">
            </div>
            <div class="form-group">
                <label for="bathroom" class="text-white text-lg">Bathroom</label>
                <input type="text" id="bathroom" required name="bathroom" class="mt-1 w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:border-blue-300">
            </div>
            <div class="form-group">
                <label for="location" class="text-white text-lg">Location</label>
                <div class="location-dropdown mt-1">
                    <select id="location" required name="location" class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring focus:border-blue-300">
                        <option value="" disabled selected>Select a location</option>
                    </select>
                </div>
            </div>
            <div class="flex justify-end">
                <button type="submit" class="px-5 py-2 bg-green-500 text-white rounded-md shadow hover:bg-green-600 transition-colors">Predict</button>
            </div>
        </form>
        <div class="mt-6 text-white">
            <h2 class="text-xl">Estimated Price for {{ area }}: {{ ans }} Lac Rupees</h2>
        </div>
    </div>
    


    <script>
        // Get the select element
        var areaSelect = document.getElementById("location");

        // Fetch JSON data from the URL
        fetch("http://127.0.0.1:8000/ehehbouy")
            .then(function(response) {
                return response.json();
            })
            .then(function(data) {
                // Populate the dropdown options
                data.area_names.forEach(function (areaName) {
                    var option = document.createElement("option");
                    option.text = areaName;
                    option.value = areaName;
                    areaSelect.appendChild(option);
                });
            })
            .catch(function(error) {
                console.error("Error fetching data: " + error);
            });
    </script>

{% endblock %}

templates/starting.html
{% extends 'base.html' %} {% block title %} House Prediction {% endblock %} 
{% block content %}
<style>
  @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

* {
  font-family: "Raleway", sans-serif;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  text-decoration: none;
  outline: none;
  border: none;
}

body {
  max-height: fit-content;
  background-color: #12141D;
  background-attachment: fixed;
  background-position: center;
  overflow-x: hidden;
}
.home-btn {
  display: flex;
  flex-direction: row;
}
.home-btn .btn-tag {
  background: #ff664f;
  color: #fff;
  font-size: 14px;
  font-weight: 600;
}


</style>
<div class="mx-auto max-w-7xl py-14  px-2 sm:px-6 lg:px-8 my-20 flex flex-col justify-center items-center text-start">
   <div>
    <p class="text-[#696B76] text-[26px] font-600" >
      We deliver the best real estate deals with perfect timing – it is very
      difficult when it's time for getting a new house with the perfect price and
      features. But worry not! It's so simple to find the best real estate deals
      in your area with our service. Here you can also sell or rent your house,
      apartment, or room. You can post your ad for free and get the best price for
      your property. You are also able to buy or rent a house or apartment. This
      website has a nationwide database of residences, which is updated every day.
      So what are you waiting for? Find the perfect location and the price
      predicted right now!
    </p>
   </div>

  <div class="home-btn my-10">
    <a href="" class="btn-tag py-3 px-4 rounded mr-4 text-[24px]">Explore Now<span class=" ml-1 align-middle"><i
                class="fa fa-angle-double-right"></i></span></a>
</div>
</div>
{% endblock %}