chat/urls.py
from django.urls import path
from chat.views.views import *

app_name = 'chats'

urlpatterns = [
    path('chat/<int:pk>/', chatroom, name='chatroom'),
    path('chat/ajax/<int:pk>/', ajax_load_messages, name='chatroom-ajax'),
    path('chatpage', chatpage, name='chatpage'),
]

myhome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static
from predict import urls as predict_urls
from posts import urls as posts_url
from homeauth import urls as homeauth_urls
from chat import urls as chat_urls

app_name = 'myhome'
urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', views.start, name='start'),
                  # path('home', views.home, name='home'),
                  # path('login', views.login, name='login'),
                  path('', include(predict_urls, namespace='predict')),
                  path('', include(posts_url, namespace='posts')),
                  path('', include(homeauth_urls, namespace='homeauth')),
                  path('', include(chat_urls, namespace='chats')),
              ] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views.views import *

app_name = 'posts'

urlpatterns = [
    path('browse', BrowserView.as_view(), name='browse'),
    path('content/<int:pk>', PostDetailsView.as_view(), name='content'),
    path('new-post/', PostCreateView.as_view(), name='new_post'),
    path('content/update/<int:pk>', PostUpdateView.as_view(), name='update_post'),
    path('content/delete/<int:pk>', PostDeleteView.as_view(), name='delete_post'),
    path('filter', filter_posts, name='filter'),
    path('content/<int:pk>/comment/', CommentView.as_view(), name='comment'),
    path('content/<int:pk>/delete', CommentDeleteView.as_view(), name='deleteComment'),
    path('', home_auth, name='home'),
]

posts/models/base_time_stamp.py
from model_utils.models import TimeStampedModel
from model_utils import FieldTracker
from django.db import IntegrityError


class BaseStampStampModel(TimeStampedModel):
    tracker = FieldTracker()

    class Meta:
        abstract = True

    def delete(self, **kwargs):
        try:
            super().delete(**kwargs)

        except IntegrityError:
            raise "Integrity Error"

posts/models/categories.py
from django.db import models
from posts.models.base_time_stamp import BaseStampStampModel


class PostCategory(BaseStampStampModel):
    CATEGORY_OPTION_CHOICES = [
        ('1', 'Sell',),
        ('2', 'Buy',),
        ('3', 'Information',),
    ]

    category = models.CharField(max_length=50, choices=CATEGORY_OPTION_CHOICES, default='1')
    value = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.get_category_display()

posts/models/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from posts.models.categories import PostCategory
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    description = RichTextField(blank=True, null=True)
    published = models.DateTimeField(default=timezone.now)
    category = models.ManyToManyField(PostCategory, related_name='categories')
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def get_absolute_url(self):
        return reverse('posts:content', args=(str(self.pk)))


# class Comment(models.Model):
#     post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
#     name = models.CharField(max_length=255)
#     body = models.TextField()
#     date_added = models.DateTimeField(default=timezone.now)
#
#     def __str__(self):
#         return '%s - %s' % (self.post.title, self.name)
#
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.owner.username)

posts/forms/forms.py
from django import forms
from posts.models.models import Post, Comment
from posts.models.categories import PostCategory


class PostForm(forms.ModelForm):
    category = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=PostCategory.CATEGORY_OPTION_CHOICES,
        required=False
    )

    class Meta:
        model = Post
        fields = ['title', 'author', 'description', 'image', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'author', 'type': 'hidden'}),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
        }


class UpdateForm(forms.ModelForm):
    category = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=PostCategory.CATEGORY_OPTION_CHOICES,
        required=False
    )

    class Meta:
        model = Post
        fields = ('title', 'description', 'category')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

        widgets = {
            'comment': forms.Textarea(attrs={'class': 'form-control'}),
        }

posts/views/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required

from posts.forms.forms import PostForm, UpdateForm, CommentForm
from posts.models.categories import PostCategory
from posts.models.models import Post, Comment

check = False


def auth(request):
    if request.user.is_authenticated:
        return True
    else:
        return False


# @login_required(login_url='/login')
def home_auth(request):
    return render(request, 'starting.html')


class BrowserView(ListView):
    model = Post
    template_name = 'posts/browse.html'
    ordering = ['-published']

    @method_decorator(login_required(login_url='/login'))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PostDetailsView(DetailView):
    model = Post
    template_name = 'posts/post_details.html'


class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create_post.html'
    # fields = ['title', 'author', 'description', 'category']


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'posts/update_post.html'
    # fields = ['title', 'description', 'category']
    form_class = UpdateForm


class PostDeleteView(DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    success_url = '/browse'


def filter_posts(request):
    if request.method == 'GET':
        selected_categories = request.GET.getlist('categories')

        # Fetch all category choices
        category_choices = PostCategory.CATEGORY_OPTION_CHOICES

        if selected_categories:
            posts = Post.objects.filter(category__in=selected_categories)
        else:
            posts = Post.objects.all()

        context = {
            'object_list': posts,
            'category_choices': category_choices,
            'selected_categories': selected_categories,  # Pass selected categories to the context
        }

        return render(request, 'posts/browse.html', context)


# class CommentView(CreateView):
#     model = Comment
#     form_class = CommentForm
#     # fields = '__all__'
#     template_name = 'posts/comment.html'
#
#     def form_valid(self, form):
#         form.instance.post_id = self.kwargs['pk']
#         return super().form_valid(form)
#
#     success_url = reverse_lazy('posts:browse')
class CommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'posts/comment.html'

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Set the comment owner to the current user
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:content', args=[self.kwargs['pk']])


class CommentDeleteView(DeleteView):
    model = Comment
    template_name = 'posts/delete_comment.html'
    success_url = '/browse'

posts/templates/posts/browse.html
{% extends 'base.html' %}
{% block title %} Browse Posts! {% endblock %}

{% block content %}
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
            font-family: "Raleway", sans-serif;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            text-decoration: none;
            outline: none;
            border: none;
        }

        body {
            max-height: fit-content;
            background-color: #12141D;
            background-attachment: fixed;
            background-position: center;
            overflow-x: hidden;
        }

        .top-button {
            top: 10%;
            left: 8%;
            z-index: 1;
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .filter-button {
            top: 10%;
            left: 30%;
            z-index: 1;
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .dropdownn-menu {
            display: none;
            position: absolute;
            {% comment %} left: 72.50%; {% endcomment %}
            top: 30%;
            z-index: 2;
            width:300px;
            height300px
            background-color: #1E2029;
            border-radius: 5px;
            padding: 20px;
        }

        .show {
            display: block;
        }
    </style>

    <div class="mx-auto max-w-7xl flex justify-between my-16">
        <button class="top-button" onclick="redirectToContent()">Add new Post</button>
        <button class="filter-button" id="categoryFilterButton" onclick="toggleDropdown()">
            Filter by Category <i class="fas fa-filter"></i>
        </button>
    </div>

    <!-- Dropdown for category filter -->
    <div id="filterDropdown" class="dropdownn-menu lg:left-[72.50%] md:left-[50%] sm:left-[45%] flex flex-end rounded bg-[#1E2029]">
        <form method="get" action="{% url 'posts:filter' %}">
            {% csrf_token %}

            <!-- Category checkboxes -->
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="1" name="categories" value="1" {% if '1' in selected_categories %}checked{% endif %}>
                <label class="form-check-label text-white" for="1">Sell</label>
                <p></p>
                <input class="form-check-input" type="checkbox" id="2" name="categories" value="2" {% if '2' in selected_categories %}checked{% endif %}>
                <label class="form-check-label text-white" for="2">Buy</label>
                <p></p>
                <input class="form-check-input" type="checkbox" id="3" name="categories" value="3" {% if '3' in selected_categories %}checked{% endif %}>
                <label class="form-check-label text-white" for="3">Information</label>
            </div>

            <div class="flex justify-between max-w-2xl my-6">
                <button type="submit" class="text-white bg-green-600 px-3 py-2 text-16px rounded">Apply Filter</button>
                <button type="button" class="text-white bg-red-600 px-3 py-2 text-16px rounded">
                    <a href="{% url 'posts:browse' %}" style="color: white">Clear Filter</a>
                </button>
            </div>
        </form>
    </div>
    <br/>
    <br/>
    <br/>
    
    <div class="mx-auto max-w-7xl my-20 sm:mt-26">
        <h2 class="text-white font-600 text-[24px]">All Posts</h2><br>
        <div class="grid 2xl:grid-cols-2 xl:grid-cols-2 lg:grid-cols-2 md:grid-cols-2 sm:grid-cols-1 gap-12 lg:gap-20 md:gap-18 sm:gap-6 bg-[#1E2029] rounded-2xl py-20 px-14 ">
            {% for post in object_list %}
            <div class="bg-[#12141D]">
                <div class="p-6 rounded-lg">
                    <div>
                        {% if post.image %}
                        <img src="{{ post.image.url }}" alt="Image for {{ post.title }}" class="w-[250px] h-[150px] object-cover"/>
                        {% else %}
                        <img src="" alt="No image available" class="w-[150px] h-[100px] object-cover"/>
                        {% endif %}
                    </div>
                    <h5 class="text-20px text-white mt-2"><a href="{% url 'posts:content' post.pk %}">{{ post.title }}</a></h5>
                    <p class="text-16px font-400 text-gray-400 mt-2">Date: {{ post.published }}</p>
                    <p class="text-18px font-600 text-gray-500 mt-2">Author: {{ post.author.first_name }} {{ post.author.last_name }}</p>
                    <p class="text-14px font-400 text-gray-500 my-2">Description: <small>{{ post.description|slice:"50"|safe }}</small></p>
                    {% if user.id == post.author.id %}
                    <div class="flex justify-between">
                        <button type="button" class="text-white bg-blue-500 px-4 py-2 text-18px rounded"><a href="{% url 'posts:update_post' post.pk %}">Edit</a></button>
                        <button type="button" class="text-white bg-red-500 px-4 py-2 text-18px rounded"><a href="{% url 'posts:delete_post' post.pk %}">Delete</a></button>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- JavaScript to toggle the dropdown menu -->
    <script>
        function toggleDropdown() {
            var dropdown = document.getElementById('filterDropdown');
            dropdown.classList.toggle('show');
        }

        function redirectToContent() {
            window.location.href = '{% url 'posts:new_post' %}';
        }
    </script>
{% endblock %}

posts/templates/posts/comment.html
{% extends 'base.html' %}
{% block title %} Add a Comment {% endblock %}
{% block content %}
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
          font-family: "Raleway", sans-serif;
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          text-decoration: none;
          outline: none;
          border: none;
        }
        
        body {
          max-height: fit-content;
          background-color: #12141D;
          background-attachment: fixed;
          background-position: center;
          overflow-x: hidden;
        }
        
        .header {
           {% comment %} position: fixed;
          top: 0;
          left: 0;
          right: 0;
          z-index: 1000;  {% endcomment %}
          background: #12141D;
          padding: 12px 6.5%;
        }
    </style>


    <div class="mx-auto max-w-7xl mt-12 p-8 bg-[#1E2029] rounded-lg shadow-lg">
        <h1 class="text-white text-[24px] font-bold mb-6">Add Comment...</h1>

        <div class="text-[#007BFF] font-400 text-[20px]">
            <form method="POST" class="space-y-6">
                {% csrf_token %}
                
                <div class="form-group space-y-4">
                    {{ form.as_p }}
                </div>
                <div class="flex justify-start">
                    <button type="submit" class="bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-6 rounded-lg transition-all duration-300">
                        Comment
                    </button>
                </div>
            </form>
        </div>
    </div>
    
{% endblock %}

posts/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} Create your new post. {% endblock %}
{% block content %}
    <style>
            @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

            * {
              font-family: "Raleway", sans-serif;
              margin: 0;
              padding: 0;
              box-sizing: border-box;
              text-decoration: none;
              outline: none;
              border: none;
            }
            
            body {
              max-height: fit-content;
              background-color: #12141D;
              background-attachment: fixed;
              background-position: center;
              overflow-x: hidden;
            }
    </style>


    <div class ="mx-auto  max-w-7xl p-6 rounded bg-[#1E2029] my-10">
        <h1 class="text-[#fff] text-[20px] mb-2"> Create your new post. </h1>

        <form class="text-[black] bg-[#f3f3f3] gap-4 p-6 rounded" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media}}
            {{ form.as_p }}
            <button class="mt-3 text-[#fff] bg-[#007BFF] px-4 py-2 text-[18px] font-600 rounded">Create Post</button>
        </form>
    </div>
    <script>
        let name = "{{ user.id }}";
        document.getElementById("author").value = name;
    </script>
{% endblock %}

posts/templates/posts/delete_comment.html
{% extends 'base.html' %}
{% block title %} Delete Post {% endblock %}
{% block content %}
    <style>
        body {
            background-color: #080710;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            color: #ffffff;
        }
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
          font-family: "Raleway", sans-serif;
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          text-decoration: none;
          outline: none;
          border: none;
        }
        
        body {
          max-height: fit-content;
          background-color: #12141D;
          background-attachment: fixed;
          background-position: center;
          overflow-x: hidden;
        }
    </style>

    <div class="container my-5">
        <h1> Delete Comment.... </h1>

        <div class="col">
            <div class="row">
                <form method="POST">
                    {% csrf_token %}
                    <p>Are you sure you want to delete this comment?</p>
                    <button class="btn btn-danger">Delete Comment</button>
                </form>
                <form>
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success" style="margin-top: 50%; margin-left: -70%">Cancel</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/delete_post.html
{% extends 'base.html' %}
{% block title %} Delete Post {% endblock %}
{% block content %}
    <style>
        {% comment %} body {
            background-color: #080710;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            color: #ffffff;
        } {% endcomment %}
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
          font-family: "Raleway", sans-serif;
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          text-decoration: none;
          outline: none;
          border: none;
        }
        
        body {
          max-height: fit-content;
          background-color: #12141D;
          background-attachment: fixed;
          background-position: center;
          overflow-x: hidden;
        }
    </style>

    <div class="mx-auto max-w-7xl my-10">
        <h1 class="text-[#fff] text-[24px] my-10"> Delete Post </h1>

        <div class="col">
            <div class="row">
                <form method="POST" class="text-[#fff] bg-[#FF5C5C] p-6 rounded max-w-2xl">
                    {% csrf_token %}
                    <p class="text-[#fff] text-[20px] mt-4">Are you sure you want to delete this post?</p>

                    {% comment %} <div class="flex flex-col">
                        
                    <button class="border-4 border-[#313239] bg-[red] mt-4 rounded text-[18px] px-2 py-3">Delete Post</button>
                    
                    <a href="{% url 'posts:browse' %}" class="border-4 border-[#313239] bg-[red] mt-4 rounded text-[18px] px-2 py-3">Delete Post</a>
                    </div> {% endcomment %}
                    
                    <div class="flex flex-between">
                        <button class="border-4 border-[#313239] bg-[red] mt-4 rounded text-[18px] px-2 py-3">Delete Post</button>
                        <a href="{% url 'posts:browse' %}" class="text-[white] px-2 py-3 text-[18px] bg-[green]">Cancel</a> 

                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_details.html
{% extends 'base.html' %}
{% block title %} Browse Posts! {% endblock %}
{% block content %}
     <style>
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
          font-family: "Raleway", sans-serif;
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          text-decoration: none;
          outline: none;
          border: none;
        }
        
        body {
          max-height: fit-content;
          background-color: #12141D;
          background-attachment: fixed;
          background-position: center;
          overflow-x: hidden;
        }
        
        .header {
           {% comment %} position: fixed;
          top: 0;
          left: 0;
          right: 0;
          z-index: 1000;  {% endcomment %}
          background: #12141D;
          padding: 12px 6.5%;
        }
    </style>
    <div class ="mx-auto max-w-7xl mt-12">

        <div class="">
            <div>
                <h1 class="text-[20px] font-600 text-white">{{ post.title }}</h1>
                <small class="text-[14px] font-400 text-gray-400">{{ post.author.first_name }} {{ post.author.last_name }}</small>
                {% if post.author.id == user.id %}
                <h5 class="h-[2px] bg-[white] mt-2"></h5>
                {% else %}
                <h5 class="text-[16px] font-400 text-gray-400"><a class="text-[14px] font-400 text-gray-400" href="{% url 'chats:chatroom' post.author.id %}">Chat with author!</a> </h5>
                {% endif %}
                <br>
                <small class="text-[14px] font-400 text-gray-400">Date: {{ post.published }}</small>
            </div>
            {% if user.id == post.author.id %}
                <div class="mt-4">
                    <button type="button" class="text-white bg-blue-500 px-4 py-2 text-18px rounded" ><a href="{% url 'posts:update_post' post.pk %}" style="color: white">Edit</a></button>
                    &nbsp;

                    <button type="button" class="text-white bg-red-500 px-4 py-2 text-18px rounded"><a href="{% url 'posts:delete_post' post.pk %}" style="color: white">Delete</a></button>
                </div>
            {% endif %}
        </div>
        <hr style="background-color: white">

        <br>
        {{ post.description | safe}}
        <br>
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="invalid" width="640" height="416">
        {% endif %}
        <hr class="h-[2px] bg-[white] mt-4">
    </div>

    <div class = 'mx-auto max-w-7xl mt-4'>
        <h4 class="text-white text-[20px] font-600">Comments</h4>
        <hr class="h-[2px] bg-[white] mt-4">
        {% if not post.comments.all %}
          <p class="text-[16px] font-400 text-gray-400">No Comments Yet...<a class="text-[16px] font-400 text-gray-400" href="{% url 'posts:comment' post.pk %}">Add One</a></p>
        {% else %}
            <a href="{% url 'posts:comment' post.pk %}" class="text-[16px] font-400 text-gray-400 mt-4">Add Comment</a>
            <br/><br/>
            {% for comment in post.comments.all %}
                {% if user.id == comment.owner.id%}
                    <strong class="text-[16px] font-400 text-gray-400 mr-2">{{ comment.owner.first_name }} {{ comment.owner.last_name }} - {{ comment.date_added }}</strong><a href="{% url 'posts:deleteComment' post.pk %}"  class="text-white bg-red-500 px-4 py-2 text-18px rounded">Delete</a>
                {% else %}
                    <strong class="text-[16px] font-400 text-gray-400 mr-2">{{ comment.owner.first_name }} {{ comment.owner.last_name }} - {{ comment.date_added }}</strong>
                {% endif %}
                <br/>
                 <small class="text-[16px] font-400 text-gray-400 mr-2">{{ comment.comment }}</small>
                <br/><br/>
            {% endfor %}

        {% endif %}
        <br>
         <br>
    </div>
{% endblock %}

posts/templates/posts/update_post.html
{% extends 'base.html' %}
{% block title %} Edit Post {% endblock %}
{% block content %}
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Raleway:wght@100;300;400;500;600&display=swap");

        * {
          font-family: "Raleway", sans-serif;
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          text-decoration: none;
          outline: none;
          border: none;
        }
        
        body {
          max-height: fit-content;
          background-color: #12141D;
          background-attachment: fixed;
          background-position: center;
          overflow-x: hidden;
        }
    </style>


    <div class = 'mx-auto  max-w-7xl p-6 rounded bg-[#1E2029] my-10'>
        <h1 class="text-[#fff] text-[20px] mb-2"> Update your post. </h1>

        <form method="POST" class="text-[black] bg-[#f3f3f3] gap-4 p-6 rounded" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <button class="mt-3 text-[#fff] bg-[#007BFF] px-4 py-2 text-[18px] font-600 rounded">Update Post</button>
        </form>
    </div>
{% endblock %}